ext {
    extName = 'BLZone'
    extClass = '.BLZone'
    extVersionCode = 10
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(':lib:filemoonextractor'))
    implementation(project(':lib:streamtapeextractor'))
    implementation(project(':lib:mixdropextractor'))
    implementation(project(':lib:vidguardextractor'))
    implementation(project(':lib:mp4uploadextractor'))
    implementation(project(':lib:voeextractor'))
    implementation(project(':lib:ruplayextractor'))
    implementation(project(':lib:embed4meextractor'))
}
